import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { checkParser, parserPython, setupParser, SQLGLOT_VERSION } from '../scripts/setup-ddl-parser.mjs';

const evaluationPython = process.env.MIGRATION_SQLGLOT_EVALUATION_PYTHON;
const evaluationModulePath = process.env.MIGRATION_SQLGLOT_EVALUATION_MODULE_PATH ?? '';

const SQLGLOT_DDL_CASES = {
    tsql: {
        dialect: 'tsql',
        expectedStatements: 3,
        minimumQuotedIdentifiers: 8,
        expectedNodes: ['alter', 'foreignkey', 'primarykeycolumnconstraint', 'schema'],
        sql: `CREATE TABLE [sales].[Orders] (
    [Id] INT NOT NULL PRIMARY KEY,
    [CustomerId] INT,
    [Total] DECIMAL(18,2),
    CONSTRAINT [FK_Orders_Customers] FOREIGN KEY ([CustomerId]) REFERENCES [sales].[Customers]([Id])
);
ALTER TABLE [sales].[Orders] ADD [CreatedAt] DATETIME2 NULL;
CREATE VIEW [sales].[OrderTotals] AS
SELECT [CustomerId], SUM([Total]) AS [Total] FROM [sales].[Orders] GROUP BY [CustomerId];`,
    },
    postgres: {
        dialect: 'postgres',
        expectedStatements: 4,
        minimumQuotedIdentifiers: 0,
        expectedNodes: ['alter', 'checkcolumnconstraint', 'generatedasidentitycolumnconstraint', 'index', 'reference'],
        sql: `CREATE TABLE public.orders (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id),
    total NUMERIC(18,2) CHECK (total >= 0)
);
ALTER TABLE public.orders ADD COLUMN created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX orders_customer_idx ON public.orders (customer_id);
CREATE VIEW public.order_totals AS
SELECT customer_id, SUM(total) AS total FROM public.orders GROUP BY customer_id;`,
    },
    mysql: {
        dialect: 'mysql',
        expectedStatements: 3,
        minimumQuotedIdentifiers: 8,
        expectedNodes: ['alter', 'autoincrementcolumnconstraint', 'foreignkey', 'indexcolumnconstraint', 'schema'],
        sql: `CREATE TABLE \`shop\`.\`orders\` (
    \`id\` BIGINT AUTO_INCREMENT PRIMARY KEY,
    \`customer_id\` BIGINT,
    \`total\` DECIMAL(18,2),
    KEY \`orders_customer_idx\` (\`customer_id\`),
    CONSTRAINT \`fk_orders_customers\` FOREIGN KEY (\`customer_id\`) REFERENCES \`shop\`.\`customers\` (\`id\`)
) ENGINE=InnoDB;
ALTER TABLE \`shop\`.\`orders\` ADD COLUMN \`created_at\` DATETIME DEFAULT CURRENT_TIMESTAMP;
CREATE VIEW \`shop\`.\`order_totals\` AS
SELECT \`customer_id\`, SUM(\`total\`) AS \`total\` FROM \`shop\`.\`orders\` GROUP BY \`customer_id\`;`,
    },
    oracle: {
        dialect: 'oracle',
        expectedStatements: 4,
        minimumQuotedIdentifiers: 8,
        expectedNodes: ['alter', 'foreignkey', 'generatedasidentitycolumnconstraint', 'primarykey', 'sequenceproperties'],
        sql: `CREATE TABLE "SALES"."ORDERS" (
    "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "CUSTOMER_ID" NUMBER,
    "TOTAL" NUMBER(18,2),
    CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ORDERS_CUSTOMERS" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "SALES"."CUSTOMERS" ("ID")
);
CREATE SEQUENCE "SALES"."ORDER_SEQ" START WITH 1 INCREMENT BY 1;
ALTER TABLE "SALES"."ORDERS" ADD ("CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE OR REPLACE VIEW "SALES"."ORDER_TOTALS" AS
SELECT "CUSTOMER_ID", SUM("TOTAL") AS "TOTAL" FROM "SALES"."ORDERS" GROUP BY "CUSTOMER_ID";`,
    },
    sqlite: {
        dialect: 'sqlite',
        expectedStatements: 4,
        minimumQuotedIdentifiers: 0,
        expectedNodes: ['alter', 'checkcolumnconstraint', 'index', 'primarykeycolumnconstraint', 'reference'],
        sql: `CREATE TABLE orders (
    id INTEGER PRIMARY KEY,
    customer_id INTEGER REFERENCES customers(id),
    total NUMERIC CHECK (total >= 0)
);
ALTER TABLE orders ADD COLUMN created_at TEXT DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX orders_customer_idx ON orders (customer_id);
CREATE VIEW order_totals AS
SELECT customer_id, SUM(total) AS total FROM orders GROUP BY customer_id;`,
    },
};

function writeChoice(workspace, choice) {
    const migrationRoot = path.join(workspace, '.cosmosdb-migration');
    fs.mkdirSync(migrationRoot);
    fs.writeFileSync(path.join(migrationRoot, 'project.json'), JSON.stringify({ phases: { discovery: { ddlParsing: choice } } }));
    return migrationRoot;
}

if (evaluationPython) {
    test('evaluates representative DDL with the pinned SQLGlot library', () => {
        const script = [
            'import json, sys',
            'module_path = sys.argv[1]',
            'module_path and sys.path.insert(0, module_path)',
            'import sqlglot',
            'cases = json.loads(sys.argv[2])',
            'results = {}',
            'for name, case in cases.items():',
            '    trees = sqlglot.parse(case["sql"], read=case["dialect"])',
            '    nodes = [node for tree in trees for node in tree.walk()]',
            '    results[name] = {"statements": len(trees), "nodes": sorted({node.key for node in nodes}), "quotedIdentifiers": sum(1 for node in nodes if node.key == "identifier" and node.args.get("quoted"))}',
            'print(json.dumps({"version": sqlglot.__version__, "results": results}))',
        ].join('\n');
        const result = spawnSync(
            evaluationPython,
            ['-I', '-c', script, evaluationModulePath, JSON.stringify(SQLGLOT_DDL_CASES)],
            { encoding: 'utf8', timeout: 30000, maxBuffer: 1024 * 1024 },
        );
        assert.equal(result.status, 0, result.stderr || result.stdout);
        const report = JSON.parse(result.stdout);
        assert.equal(report.version, SQLGLOT_VERSION);
        for (const [name, ddlCase] of Object.entries(SQLGLOT_DDL_CASES)) {
            assert.equal(report.results[name].statements, ddlCase.expectedStatements, name);
            assert(
                report.results[name].quotedIdentifiers >= ddlCase.minimumQuotedIdentifiers,
                `${name}: quoted identifiers`,
            );
            for (const node of ddlCase.expectedNodes) assert(report.results[name].nodes.includes(node), `${name}: ${node}`);
        }
    });
}

test('checking a missing parser performs no installation or filesystem writes', () => {
    const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'parser-check-'));
    try {
        assert.equal(setupParser({ workspace }, () => { throw new Error('must not execute setup'); }).ready, false);
        assert.deepEqual(fs.readdirSync(workspace), []);
    } finally { fs.rmSync(workspace, { recursive: true }); }
});

test('saved model-only choice prevents installation and subprocess execution', () => {
    const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'parser-opt-out-'));
    try {
        const migrationRoot = writeChoice(workspace, { method: 'model', decisionSource: 'explicit' });
        const projectPath = path.join(migrationRoot, 'project.json');
        const content = fs.readFileSync(projectPath, 'utf8');
        const result = setupParser({ workspace, install: true }, () => { throw new Error('must not spawn'); });
        assert.equal(result.method, 'model');
        assert.equal(result.ready, false);
        assert.deepEqual(fs.readdirSync(migrationRoot), ['project.json']);
        assert.equal(fs.readFileSync(projectPath, 'utf8'), content);
    } finally { fs.rmSync(workspace, { recursive: true }); }
});

test('missing unattended-default SQLGlot warns and continues with model-only fallback', () => {
    const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'parser-fallback-'));
    try {
        writeChoice(workspace, { method: 'sqlglot', decisionSource: 'unattended-default' });
        const result = setupParser({ workspace });
        assert.equal(result.abort, false);
        assert.equal(result.method, 'model');
        assert.equal(result.fallbackFrom, 'sqlglot');
        assert.equal(result.fallbackReason, 'unavailable');
        assert.match(result.warning, /continuing.*model-only/iu);
    } finally { fs.rmSync(workspace, { recursive: true }); }
});

test('missing explicitly selected SQLGlot requires installation or abort', () => {
    const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'parser-required-'));
    try {
        writeChoice(workspace, { method: 'sqlglot', decisionSource: 'interactive' });
        const result = setupParser({ workspace });
        assert.equal(result.abort, true);
        assert.equal(result.method, 'sqlglot');
        assert.match(result.reason, /Explicitly selected SQLGlot is unavailable/u);
    } finally { fs.rmSync(workspace, { recursive: true }); }
});

test('failed unattended installation falls back but failed explicit installation aborts', () => {
    for (const decisionSource of ['unattended-default', 'explicit']) {
        const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'parser-install-'));
        try {
            writeChoice(workspace, { method: 'sqlglot', decisionSource });
            const result = setupParser(
                { workspace, install: true },
                () => ({ status: 1, stderr: 'installation unavailable' }),
            );
            assert.equal(result.abort, decisionSource === 'explicit');
            assert.equal(result.method, decisionSource === 'explicit' ? 'sqlglot' : 'model');
        } finally { fs.rmSync(workspace, { recursive: true }); }
    }
});

test('refuses to overwrite an invalid existing parser environment', () => {
    const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'parser-check-'));
    try {
        fs.mkdirSync(path.dirname(parserPython(workspace)), { recursive: true });
        assert.throws(() => setupParser({ workspace, install: true }), /Existing parser environment/);
    } finally { fs.rmSync(workspace, { recursive: true }); }
});

test('treats an invalid existing environment as unavailable without overwriting it', () => {
    for (const decisionSource of ['unattended-default', 'interactive']) {
        const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'parser-invalid-'));
        try {
            writeChoice(workspace, { method: 'sqlglot', decisionSource });
            fs.mkdirSync(path.dirname(parserPython(workspace)), { recursive: true });
            const result = setupParser({ workspace, install: true });
            assert.equal(result.abort, decisionSource === 'interactive');
            assert.equal(result.method, decisionSource === 'interactive' ? 'sqlglot' : 'model');
            assert.match(result.reason, /Existing parser environment is invalid/u);
        } finally { fs.rmSync(workspace, { recursive: true }); }
    }
});

test('blocks parser environments outside the workspace', { skip: process.platform === 'win32' }, () => {
    const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'parser-check-'));
    try {
        fs.symlinkSync(os.tmpdir(), path.join(workspace, '.cosmosdb-migration'));
        assert.throws(() => checkParser(workspace), /inside the workspace/);
    } finally { fs.rmSync(workspace, { recursive: true }); }
});
