/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { type CosmosContainer, type CosmosModel, type IndexingPolicy } from '../cosmosModel';

/**
 * Cosmos DB Built-in Data Contributor role definition id (data-plane RBAC).
 * Same id used by `addRbacContributorPermission()` in `src/cosmosdb/utils/rbacUtils.ts`.
 */
const DATA_CONTRIBUTOR_ROLE_ID = '00000000-0000-0000-0000-000000000002';

/** Default database name when the model does not specify one. */
const DEFAULT_DATABASE_NAME = 'migration';

/**
 * The set of values that can be supplied via `main.bicepparam`. Subscription
 * and resource group are deliberately not parameters — they are *deployment
 * scope* and are passed to `az deployment group create` directly.
 */
export interface BicepParamValues {
    accountName?: string;
    location?: string;
    databaseName?: string;
    principalId?: string;
    disableLocalAuth?: boolean;
    /** Suggested deployment-scope breadcrumbs — emitted as comments only. */
    subscriptionId?: string;
    resourceGroup?: string;
}

/** Header banner placed at the top of every generated file. */
const GENERATED_BANNER = [
    '// ----------------------------------------------------------------------------',
    '// Generated by the Azure Cosmos DB Migration Assistant.',
    '// Safe to edit; the assistant only regenerates this file until you refine it',
    '// (i.e. proceed past the resource-group / account-name selection in Phase 4).',
    '// ----------------------------------------------------------------------------',
    '',
];

// ─── Public API ─────────────────────────────────────────────────────

/**
 * Build a `main.bicep` template that provisions the Cosmos DB account,
 * database, containers, and a SqlRoleAssignment for the deployer, mirroring
 * what `provisionAccount()` + `runProvisioning()` create via the SDK.
 */
export function buildBicepTemplate(model: CosmosModel): string {
    const databaseName = model.databaseName ?? DEFAULT_DATABASE_NAME;
    const isProvisioned = model.capacityMode === 'provisioned';
    const lines: string[] = [];

    lines.push(...GENERATED_BANNER);
    lines.push("targetScope = 'resourceGroup'");
    lines.push('');

    // ─── Parameters ─────────────────────────────────────────────────
    lines.push("@description('Name of the Cosmos DB account. 3-44 chars, lowercase letters, digits, and hyphens.')");
    lines.push('@minLength(3)');
    lines.push('@maxLength(44)');
    lines.push('param accountName string');
    lines.push('');
    lines.push("@description('Azure region for the account. Defaults to the resource group location.')");
    lines.push('param location string = resourceGroup().location');
    lines.push('');
    lines.push("@description('Name of the SQL database created inside the account.')");
    lines.push(`param databaseName string = '${escapeBicepString(databaseName)}'`);
    lines.push('');
    lines.push(
        "@description('Object id of the principal that should receive the Cosmos DB Built-in Data Contributor role. Defaults to the user/identity running the deployment.')",
    );
    lines.push('param principalId string = deployer().objectId');
    lines.push('');
    lines.push(
        "@description('When true, account keys are disabled and only Entra ID (RBAC) auth is allowed. Set to false to also enable key-based auth.')",
    );
    lines.push('param disableLocalAuth bool = true');
    lines.push('');

    // ─── Account ───────────────────────────────────────────────────
    lines.push("resource account 'Microsoft.DocumentDB/databaseAccounts@2024-05-15' = {");
    lines.push('  name: accountName');
    lines.push('  location: location');
    lines.push("  kind: 'GlobalDocumentDB'");
    lines.push('  properties: {');
    lines.push("    databaseAccountOfferType: 'Standard'");
    lines.push('    locations: [');
    lines.push('      {');
    lines.push('        locationName: location');
    lines.push('        failoverPriority: 0');
    lines.push('        isZoneRedundant: false');
    lines.push('      }');
    lines.push('    ]');
    lines.push('    disableLocalAuth: disableLocalAuth');
    if (!isProvisioned) {
        lines.push('    capabilities: [');
        lines.push('      {');
        lines.push("        name: 'EnableServerless'");
        lines.push('      }');
        lines.push('    ]');
    } else {
        lines.push('    capabilities: []');
    }
    lines.push('  }');
    lines.push('}');
    lines.push('');

    // ─── SQL Database ──────────────────────────────────────────────
    lines.push("resource sqlDatabase 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases@2024-05-15' = {");
    lines.push('  parent: account');
    lines.push('  name: databaseName');
    lines.push('  properties: {');
    lines.push('    resource: {');
    lines.push('      id: databaseName');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');

    // ─── Containers ────────────────────────────────────────────────
    for (let i = 0; i < model.containers.length; i++) {
        const container = model.containers[i];
        const symbolName = `container_${i}`;
        emitContainerResource(lines, symbolName, container, isProvisioned);
        lines.push('');
    }

    // ─── Role Assignment ───────────────────────────────────────────
    lines.push("@description('Cosmos DB Built-in Data Contributor role definition.')");
    lines.push(
        `var dataContributorRoleDefinitionId = resourceId('Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions', accountName, '${DATA_CONTRIBUTOR_ROLE_ID}')`,
    );
    lines.push('');
    lines.push(
        "resource dataContributorAssignment 'Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments@2024-05-15' = {",
    );
    lines.push('  parent: account');
    lines.push('  name: guid(account.id, principalId, dataContributorRoleDefinitionId)');
    lines.push('  properties: {');
    lines.push('    principalId: principalId');
    lines.push('    roleDefinitionId: dataContributorRoleDefinitionId');
    lines.push('    scope: account.id');
    lines.push('  }');
    lines.push('}');
    lines.push('');

    // ─── Outputs ───────────────────────────────────────────────────
    lines.push('output accountEndpoint string = account.properties.documentEndpoint');
    lines.push('output accountName string = account.name');
    lines.push('output databaseName string = sqlDatabase.name');
    lines.push('');

    return lines.join('\n');
}

/**
 * Build a `main.bicepparam` companion file. Unset values are emitted as
 * commented `// TODO` placeholders so users can fill them in before running
 * `az deployment group create`. `subscriptionId` and `resourceGroup` are
 * not Bicep parameters; they are written as breadcrumb comments at the top
 * to document the intended deployment scope.
 */
export function buildBicepParams(values: BicepParamValues = {}): string {
    const lines: string[] = [];
    lines.push(...GENERATED_BANNER);
    lines.push("using './main.bicep'");
    lines.push('');

    if (values.subscriptionId || values.resourceGroup) {
        lines.push('// Suggested deployment target:');
        if (values.subscriptionId) {
            lines.push(`//   az account set --subscription ${values.subscriptionId}`);
        }
        if (values.resourceGroup) {
            lines.push(`//   az deployment group create --resource-group ${values.resourceGroup} \\`);
            lines.push('//       --template-file main.bicep --parameters main.bicepparam');
        }
        lines.push('');
    }

    emitParamLine(lines, 'accountName', values.accountName, 'string');
    emitParamLine(lines, 'location', values.location, 'string');
    emitParamLine(lines, 'databaseName', values.databaseName, 'string');
    emitParamLine(lines, 'principalId', values.principalId, 'string');
    emitParamLine(lines, 'disableLocalAuth', values.disableLocalAuth, 'bool');
    lines.push('');

    return lines.join('\n');
}

/**
 * Parse a generated `.bicepparam` file and return the values it currently
 * declares. Used during refinement to merge new fields into a user-edited
 * file without losing comments / order. Unknown lines are preserved by
 * `mergeBicepParams`; this function only extracts the four fields we own.
 */
export function parseBicepParams(content: string): BicepParamValues {
    const result: BicepParamValues = {};
    // Only matches active (uncommented) `param NAME = …` lines.
    const stringPattern = /^param\s+(\w+)\s*=\s*'([^']*)'\s*$/;
    const boolPattern = /^param\s+(\w+)\s*=\s*(true|false)\s*$/;
    for (const rawLine of content.split(/\r?\n/)) {
        const line = rawLine.trim();
        if (!line || line.startsWith('//')) continue;

        const stringMatch = line.match(stringPattern);
        if (stringMatch) {
            const [, name, value] = stringMatch;
            if (name === 'accountName' || name === 'location' || name === 'databaseName' || name === 'principalId') {
                result[name] = value;
            }
            continue;
        }

        const boolMatch = line.match(boolPattern);
        if (boolMatch) {
            const [, name, value] = boolMatch;
            if (name === 'disableLocalAuth') {
                result.disableLocalAuth = value === 'true';
            }
        }
    }
    return result;
}

/**
 * Merge `partial` into the values currently stored in an existing
 * `main.bicepparam` file body and return a freshly emitted body.
 * Subscription / resource-group breadcrumbs in `partial` are honoured.
 * Existing comments outside of the four owned `param` lines are not
 * preserved verbatim — the file is rewritten from scratch using the
 * union of (existing values, new values).
 */
export function mergeBicepParams(existing: string, partial: BicepParamValues): string {
    const previous = parseBicepParams(existing);
    const previousScope = extractScopeBreadcrumb(existing);
    return buildBicepParams({
        ...previous,
        ...stripUndefined(partial),
        subscriptionId: partial.subscriptionId ?? previousScope.subscriptionId,
        resourceGroup: partial.resourceGroup ?? previousScope.resourceGroup,
    });
}

// ─── Internal helpers ───────────────────────────────────────────────

function emitContainerResource(
    lines: string[],
    symbolName: string,
    container: CosmosContainer,
    isProvisioned: boolean,
): void {
    const partitionKeyPaths = container.partitionKeys?.map((pk) => pk.path) ?? ['/id'];
    const partitionKeyKind = partitionKeyPaths.length > 1 ? 'MultiHash' : 'Hash';

    lines.push(`resource ${symbolName} 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-05-15' = {`);
    lines.push('  parent: sqlDatabase');
    lines.push(`  name: '${escapeBicepString(container.name)}'`);
    lines.push('  properties: {');
    lines.push('    resource: {');
    lines.push(`      id: '${escapeBicepString(container.name)}'`);
    lines.push('      partitionKey: {');
    lines.push(`        paths: [${partitionKeyPaths.map((p) => `'${escapeBicepString(p)}'`).join(', ')}]`);
    lines.push(`        kind: '${partitionKeyKind}'`);
    lines.push('        version: 2');
    lines.push('      }');
    if (container.indexingPolicy) {
        emitIndexingPolicy(lines, container.indexingPolicy, '      ');
    }
    lines.push('    }');
    if (isProvisioned && container.maxThroughput) {
        lines.push('    options: {');
        lines.push('      autoscaleSettings: {');
        lines.push(`        maxThroughput: ${container.maxThroughput}`);
        lines.push('      }');
        lines.push('    }');
    } else {
        lines.push('    options: {}');
    }
    lines.push('  }');
    lines.push('}');
}

function emitIndexingPolicy(lines: string[], policy: IndexingPolicy, indent: string): void {
    lines.push(`${indent}indexingPolicy: {`);
    lines.push(`${indent}  indexingMode: '${escapeBicepString(policy.indexingMode ?? 'consistent')}'`);
    lines.push(`${indent}  automatic: ${policy.automatic ?? true}`);

    lines.push(`${indent}  includedPaths: [`);
    for (const p of policy.includedPaths ?? []) {
        lines.push(`${indent}    {`);
        lines.push(`${indent}      path: '${escapeBicepString(p.path)}'`);
        lines.push(`${indent}    }`);
    }
    lines.push(`${indent}  ]`);

    lines.push(`${indent}  excludedPaths: [`);
    for (const p of policy.excludedPaths ?? []) {
        lines.push(`${indent}    {`);
        lines.push(`${indent}      path: '${escapeBicepString(p.path)}'`);
        lines.push(`${indent}    }`);
    }
    lines.push(`${indent}  ]`);

    if (policy.compositeIndexes && policy.compositeIndexes.length > 0) {
        lines.push(`${indent}  compositeIndexes: [`);
        for (const group of policy.compositeIndexes) {
            lines.push(`${indent}    [`);
            for (const entry of group) {
                lines.push(`${indent}      {`);
                lines.push(`${indent}        path: '${escapeBicepString(entry.path)}'`);
                lines.push(`${indent}        order: '${escapeBicepString(entry.order)}'`);
                lines.push(`${indent}      }`);
            }
            lines.push(`${indent}    ]`);
        }
        lines.push(`${indent}  ]`);
    }

    lines.push(`${indent}}`);
}

function emitParamLine(
    lines: string[],
    name: string,
    value: string | boolean | undefined,
    type: 'string' | 'bool',
): void {
    if (value === undefined || value === '') {
        lines.push(`// TODO: param ${name} = ${type === 'string' ? "'<value>'" : 'true'}`);
        return;
    }
    if (type === 'string') {
        lines.push(`param ${name} = '${escapeBicepString(String(value))}'`);
    } else {
        lines.push(`param ${name} = ${value ? 'true' : 'false'}`);
    }
}

function extractScopeBreadcrumb(content: string): { subscriptionId?: string; resourceGroup?: string } {
    const result: { subscriptionId?: string; resourceGroup?: string } = {};
    const subMatch = content.match(/az account set --subscription\s+(\S+)/);
    if (subMatch) result.subscriptionId = subMatch[1];
    const rgMatch = content.match(/--resource-group\s+(\S+)/);
    if (rgMatch) result.resourceGroup = rgMatch[1];
    return result;
}

function stripUndefined<T extends object>(obj: T): Partial<T> {
    const out: Partial<T> = {};
    for (const [k, v] of Object.entries(obj) as [keyof T, T[keyof T]][]) {
        if (v !== undefined) out[k] = v;
    }
    return out;
}

/**
 * Escape a value that will be embedded inside a single-quoted Bicep string.
 * Bicep uses backslash escapes for `'`, `\`, and a handful of control chars.
 */
function escapeBicepString(value: string): string {
    return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r/g, '\\r').replace(/\n/g, '\\n');
}
