/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { type CosmosModel } from '../cosmosModel';

export interface SampleDataResult {
    sampleData: {
        containerName: string;
        items: Record<string, unknown>[];
    }[];
}

/**
 * Generates a CosmosDB Shell (.csh) seed script from a Cosmos DB model.
 * The script reads sample data from a companion JSON file at runtime
 * using `cat` and iterates containers with `for` loops.
 *
 * Usage:
 *   cosmosshell -c seed-data.csh "<connection-string>" "sample-data.json"
 * or for Azure AD:
 *   cosmosshell -k "azconnect <endpoint>" seed-data.csh "sample-data.json"
 *
 * @param model The Cosmos DB model from Phase 3
 * @param databaseName The target database name
 * @param targetType Whether the target is an emulator or Azure account
 */
export function generateSeedScript(
    model: CosmosModel,
    databaseName: string,
    targetType: 'emulator' | 'azure' | 'provision',
): string {
    const lines: string[] = [];

    // Header
    lines.push('# ─────────────────────────────────────────────────────────────────');
    lines.push('# Cosmos DB Seed Script');
    lines.push('# Generated by Azure Databases Migration Assistant');
    lines.push('#');
    if (targetType === 'emulator') {
        lines.push('# Usage: cosmosshell -c \'seed-data.csh "<emulator-connection-string>" "sample-data.json"\'');
    } else {
        lines.push(
            '# Usage (connection string): cosmosshell -c \'seed-data.csh "<connection-string>" "sample-data.json"\'',
        );
        lines.push('# Usage (Entra ID):          cosmosshell -c \'seed-data.csh "<endpoint-url>" "sample-data.json"\'');
    }
    lines.push('# ─────────────────────────────────────────────────────────────────');
    lines.push('');

    // Connect
    if (targetType === 'emulator') {
        lines.push('# Connect to the Cosmos DB Emulator');
        lines.push("connect '$1'");
    } else {
        lines.push('# Connect to Azure Cosmos DB');
        lines.push('# Pass the connection string or Entra ID as $1');
        lines.push("connect '$1'");
    }
    lines.push('');

    // Create database
    lines.push(`# Create database "${databaseName}"`);
    lines.push(`create database ${escapeShellArg(databaseName)}`);
    lines.push('');

    const dbArg = escapeShellArg(databaseName);

    // Create containers
    for (const container of model.containers) {
        const partitionKeyPaths = container.partitionKeys?.map((pk) => pk.path) ?? ['/id'];
        const partitionKeyArg = partitionKeyPaths.join(',');

        lines.push(`# ── Container: ${container.name} ──`);

        const conArg = escapeShellArg(container.name);

        let cmd = `create container ${conArg} ${partitionKeyArg} --database=${dbArg}`;

        if (container.indexingPolicy) {
            const policyJson = JSON.stringify(container.indexingPolicy);
            cmd += ` --index_policy='${escapeJsonForShell(policyJson)}'`;
        }

        if (model.capacityMode === 'provisioned' && container.maxThroughput) {
            cmd += ` --max_throughput=${container.maxThroughput}`;
        }

        lines.push(cmd);
        lines.push('');
    }

    // Read sample data from the companion JSON file ($2)
    lines.push('# ── Insert sample data ──');
    lines.push('$data = (cat $2)');
    lines.push('for $entry in $data.sampleData {');
    lines.push(`    echo $entry.items | mkitem --database=${dbArg} --container=$entry.containerName`);
    lines.push('}');
    lines.push('');

    lines.push('echo "Seed data inserted successfully."');

    return lines.join('\n');
}

/**
 * Escapes a string for use as a CosmosDB Shell argument.
 * If the string contains spaces or special characters, wraps it in double quotes.
 */
function escapeShellArg(value: string): string {
    if (/^[a-zA-Z0-9_.-]+$/.test(value)) {
        return value;
    }
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * Escapes a JSON string for embedding inside single-quoted shell strings.
 * Single quotes in the JSON are replaced with the shell escape sequence.
 * Backslashes are literal inside single quotes and must NOT be doubled.
 */
function escapeJsonForShell(json: string): string {
    // In single-quoted strings, only single quotes need escaping.
    // Use the '\'' technique: end quote, escaped quote, start quote
    return json.replace(/'/g, "'\\''");
}
