steps:
- task: NodeTool@0
  displayName: 'Use Node'
  inputs:
    versionSource: fromFile
    versionFilePath: .nvmrc

- pwsh: corepack enable && corepack prepare --activate
  displayName: 'Install pnpm'

- pwsh: pnpm install --frozen-lockfile
  displayName: 'Install Dependencies'

- pwsh: pnpm run build
  displayName: 'Build'
