steps:
- script: |
    sudo cp .azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
    sudo chmod +x /etc/init.d/xvfb
    sudo update-rc.d xvfb defaults
    sudo service xvfb start
  displayName: 'Start X Virtual Frame Buffer'
  condition: eq(variables['Agent.OS'], 'Linux')

- task: Npm@1
  displayName: 'Test'
  inputs:
    command: custom
    customCommand: test
  env:
    SERVICE_PRINCIPAL_CLIENT_ID: $(SERVICE_PRINCIPAL_CLIENT_ID)
    SERVICE_PRINCIPAL_SECRET: $(SERVICE_PRINCIPAL_SECRET)
    SERVICE_PRINCIPAL_DOMAIN: $(SERVICE_PRINCIPAL_DOMAIN)
    DISPLAY: :10 # Only necessary for linux test

- task: Npm@1
  displayName: 'Unit Test + Coverage'
  inputs:
    command: custom
    customCommand: run vitest:coverage -- --reporter=default --reporter=junit --outputFile=vitest-results.xml

- task: PublishTestResults@2
  displayName: 'Publish Unit Test Results'
  inputs:
    testResultsFiles: 'vitest-results.xml'
    testRunTitle: 'Vitest - $(Agent.OS)'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    failIfCoverageEmpty: true
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Integration Test Results'
  inputs:
    testResultsFiles: '*-results.xml'
    testRunTitle: 'Integration - $(Agent.OS)'
  condition: succeededOrFailed()
