# Trigger the build whenever `main` or `rel/*` is updated
trigger:
  - main
  - rel/*

# Disable PR trigger
pr: none

# Scheduled nightly build of `main`
schedules:
  - cron: '0 0 * * *'
    displayName: Nightly scheduled build
    always: false # Don't rebuild if there haven't been changes
    branches:
      include:
        - main

# `resources` specifies the location of templates to pick up, use it to get 1ES templates
resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

parameters:
  - name: enableLongRunningTests
    displayName: Enable Long Running Tests
    type: boolean
    default: true
  - name: enableSigning
    type: boolean
    default: true

variables:
  # Required by MicroBuild template
  - name: TeamName
    value: 'Azure Tools for VS Code'

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@1esPipelines
  parameters:
    sdl:
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.config\guardian\.gdnsuppress
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.azure-pipelines\compliance\CredScanSuppressions.json
      # codeql:
      #   enabled: true # TODO: would like to enable only on scheduled builds but CodeQL cannot currently be disabled per https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/1es-codeql
    pool:
      name: VSEngSS-MicroBuild2022-1ES # Name of your hosted pool
      image: server2022-microbuildVS2022-1es # Name of the image in your pool. If not specified, first image of the pool is used
      os: windows # OS of the image. Allowed values: windows, linux, macOS
    stages:
      # Execute stages from the AzExt stages template
      - template: ./1esstages.yml
        parameters:
          useAzureFederatedCredentials: ${{ parameters.enableLongRunningTests }}
          enableSigning: ${{ parameters.enableSigning }}
